name: Build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: stable
      - name: Build
        run: |
          flutter build web --release --base-href /flutterwebsites/minimal/
          mv build/web/* clone_dir/flutterwebsites/minimal
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Get time in seconds
        id: seconds
        run: echo "::set-output name=seconds::$(date +'%s')"
      - name: Push build commit
        run: |
          cd clone_dir
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *
          git commit -m "Build Minimal ${{ steps.date.outputs.date }} (${{ steps.seconds.outputs.seconds }})"
          git pull --rebase
          git push
